//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Abp.Domain.Entities;

namespace JIT.DIME2Barcode.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_MOBillList:Entity<string>
    {
        [NotMapped]
        public override string Id { get; set; }
        [Key]
        public string 任务单号 { get; set; }
        public string 状态 { get; set; }
        public string 销售订单 { get; set; }
        public string 车间 { get; set; }
        public string 产品编码 { get; set; }
        public string 产品名称 { get; set; }
        public string 规格型号 { get; set; }
        public string 单位 { get; set; }
        public string 批号 { get; set; }
        public decimal 计划生产数量 { get; set; }
        public decimal 入库数量 { get; set; }
        public Nullable<System.DateTime> 计划开工日期 { get; set; }
        public Nullable<System.DateTime> 计划完工日期 { get; set; }
        public int FMOInterID { get; set; }
        public short FStatus { get; set; }
        public int FItemID { get; set; }

    }
}
