using System;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

namespace JIT.DIME2Barcode.Migrations
{
    public partial class Add_Entity_ICItemSync : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "t_ICItem",
                columns: table => new
                {
                    FItemID = table.Column<int>(nullable: false)
                        .Annotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn),
                    FModel = table.Column<string>(nullable: true),
                    FName = table.Column<string>(nullable: true),
                    FHelpCode = table.Column<string>(nullable: true),
                    FDeleted = table.Column<short>(nullable: true),
                    FShortNumber = table.Column<string>(nullable: true),
                    FNumber = table.Column<string>(nullable: true),
                    FModifyTime = table.Column<byte[]>(nullable: true),
                    FParentID = table.Column<int>(nullable: true),
                    FBrNo = table.Column<string>(nullable: true),
                    FTopID = table.Column<int>(nullable: true),
                    FRP = table.Column<short>(nullable: true),
                    FOmortize = table.Column<short>(nullable: true),
                    FOmortizeScale = table.Column<short>(nullable: true),
                    FForSale = table.Column<bool>(nullable: true),
                    FStaCost = table.Column<double>(nullable: true),
                    FOrderPrice = table.Column<double>(nullable: true),
                    FOrderMethod = table.Column<int>(nullable: true),
                    FPriceFixingType = table.Column<int>(nullable: true),
                    FSalePriceFixingType = table.Column<int>(nullable: true),
                    FPerWastage = table.Column<double>(nullable: true),
                    FARAcctID = table.Column<int>(nullable: true),
                    FPlanPriceMethod = table.Column<short>(nullable: true),
                    FPlanClass = table.Column<short>(nullable: true),
                    FErpClsID = table.Column<int>(nullable: true),
                    FUnitID = table.Column<int>(nullable: true),
                    FUnitGroupID = table.Column<int>(nullable: true),
                    FDefaultLoc = table.Column<int>(nullable: true),
                    FSPID = table.Column<int>(nullable: true),
                    FSource = table.Column<int>(nullable: true),
                    FQtyDecimal = table.Column<short>(nullable: true),
                    FLowLimit = table.Column<decimal>(nullable: true),
                    FHighLimit = table.Column<decimal>(nullable: true),
                    FSecInv = table.Column<decimal>(nullable: true),
                    FUseState = table.Column<int>(nullable: true),
                    FIsEquipment = table.Column<bool>(nullable: true),
                    FEquipmentNum = table.Column<string>(nullable: true),
                    FIsSparePart = table.Column<bool>(nullable: true),
                    FFullName = table.Column<string>(nullable: true),
                    FSecUnitID = table.Column<int>(nullable: true),
                    FSecCoefficient = table.Column<decimal>(nullable: true),
                    FSecUnitDecimal = table.Column<int>(nullable: true),
                    FAlias = table.Column<string>(nullable: true),
                    FOrderUnitID = table.Column<int>(nullable: true),
                    FSaleUnitID = table.Column<int>(nullable: true),
                    FStoreUnitID = table.Column<int>(nullable: true),
                    FProductUnitID = table.Column<int>(nullable: true),
                    FApproveNo = table.Column<string>(nullable: true),
                    FAuxClassID = table.Column<int>(nullable: true),
                    FTypeID = table.Column<int>(nullable: true),
                    FPreDeadLine = table.Column<int>(nullable: true),
                    FSerialClassID = table.Column<int>(nullable: true),
                    FOrderRector = table.Column<int>(nullable: true),
                    FPOHghPrcMnyType = table.Column<int>(nullable: true),
                    FPOHighPrice = table.Column<decimal>(nullable: true),
                    FWWHghPrc = table.Column<decimal>(nullable: true),
                    FWWHghPrcMnyType = table.Column<int>(nullable: true),
                    FSOLowPrc = table.Column<decimal>(nullable: true),
                    FSOLowPrcMnyType = table.Column<int>(nullable: true),
                    FIsSale = table.Column<bool>(nullable: true),
                    FProfitRate = table.Column<decimal>(nullable: true),
                    FSalePrice = table.Column<decimal>(nullable: true),
                    FBatchManager = table.Column<bool>(nullable: true),
                    FISKFPeriod = table.Column<bool>(nullable: true),
                    FKFPeriod = table.Column<decimal>(nullable: true),
                    FTrack = table.Column<int>(nullable: true),
                    FPlanPrice = table.Column<decimal>(nullable: true),
                    FPriceDecimal = table.Column<short>(nullable: true),
                    FAcctID = table.Column<int>(nullable: true),
                    FSaleAcctID = table.Column<int>(nullable: true),
                    FCostAcctID = table.Column<int>(nullable: true),
                    FAPAcctID = table.Column<int>(nullable: true),
                    FGoodSpec = table.Column<int>(nullable: true),
                    FCostProject = table.Column<int>(nullable: true),
                    FIsSnManage = table.Column<bool>(nullable: true),
                    FStockTime = table.Column<bool>(nullable: true),
                    FBookPlan = table.Column<bool>(nullable: true),
                    FBeforeExpire = table.Column<int>(nullable: true),
                    FTaxRate = table.Column<int>(nullable: true),
                    FAdminAcctID = table.Column<int>(nullable: true),
                    FNote = table.Column<string>(nullable: true),
                    FIsSpecialTax = table.Column<bool>(nullable: true),
                    FSOHighLimit = table.Column<decimal>(nullable: true),
                    FSOLowLimit = table.Column<decimal>(nullable: true),
                    FOIHighLimit = table.Column<decimal>(nullable: true),
                    FOILowLimit = table.Column<decimal>(nullable: true),
                    FDaysPer = table.Column<int>(nullable: true),
                    FLastCheckDate = table.Column<DateTime>(nullable: true),
                    FCheckCycle = table.Column<int>(nullable: true),
                    FCheckCycUnit = table.Column<int>(nullable: true),
                    FStockPrice = table.Column<decimal>(nullable: true),
                    FABCCls = table.Column<string>(nullable: true),
                    FBatchQty = table.Column<double>(nullable: true),
                    FClass = table.Column<bool>(nullable: true),
                    FCostDiffRate = table.Column<double>(nullable: true),
                    FDepartment = table.Column<int>(nullable: true),
                    FSaleTaxAcctID = table.Column<int>(nullable: true),
                    FCBBmStandardID = table.Column<int>(nullable: true),
                    FCBRestore = table.Column<int>(nullable: true),
                    FPickHighLimit = table.Column<decimal>(nullable: true),
                    FPickLowLimit = table.Column<decimal>(nullable: true),
                    FPlanTrategy = table.Column<int>(nullable: true),
                    FOrderTrategy = table.Column<int>(nullable: true),
                    FLeadTime = table.Column<float>(nullable: true),
                    FFixLeadTime = table.Column<float>(nullable: true),
                    FTotalTQQ = table.Column<int>(nullable: true),
                    FQtyMin = table.Column<decimal>(nullable: true),
                    FQtyMax = table.Column<decimal>(nullable: true),
                    FCUUnitID = table.Column<int>(nullable: true),
                    FOrderInterVal = table.Column<int>(nullable: true),
                    FBatchAppendQty = table.Column<decimal>(nullable: true),
                    FOrderPoint = table.Column<decimal>(nullable: true),
                    FBatFixEconomy = table.Column<decimal>(nullable: true),
                    FBatChangeEconomy = table.Column<decimal>(nullable: true),
                    FRequirePoint = table.Column<int>(nullable: true),
                    FPlanPoint = table.Column<int>(nullable: true),
                    FDefaultRoutingID = table.Column<int>(nullable: true),
                    FDefaultWorkTypeID = table.Column<int>(nullable: true),
                    FProductPrincipal = table.Column<int>(nullable: true),
                    FDailyConsume = table.Column<decimal>(nullable: true),
                    FMRPCon = table.Column<bool>(nullable: true),
                    FPlanner = table.Column<int>(nullable: true),
                    FPutInteger = table.Column<bool>(nullable: true),
                    FInHighLimit = table.Column<decimal>(nullable: true),
                    FInLowLimit = table.Column<decimal>(nullable: true),
                    FLowestBomCode = table.Column<int>(nullable: true),
                    FMRPOrder = table.Column<bool>(nullable: true),
                    FIsCharSourceItem = table.Column<int>(nullable: true),
                    FCharSourceItemID = table.Column<int>(nullable: true),
                    FPlanMode = table.Column<int>(nullable: true),
                    FCtrlType = table.Column<int>(nullable: true),
                    FCtrlStraregy = table.Column<int>(nullable: true),
                    FContainerName = table.Column<string>(nullable: true),
                    FKanBanCapability = table.Column<int>(nullable: true),
                    FIsBackFlush = table.Column<int>(nullable: true),
                    FBackFlushStockID = table.Column<int>(nullable: true),
                    FBackFlushSPID = table.Column<int>(nullable: true),
                    F_102 = table.Column<double>(nullable: true),
                    F_103 = table.Column<double>(nullable: true),
                    F_104 = table.Column<string>(nullable: true),
                    F_105 = table.Column<int>(nullable: true),
                    F_106 = table.Column<int>(nullable: true),
                    F_107 = table.Column<string>(nullable: true),
                    F_108 = table.Column<int>(nullable: true),
                    FChartNumber = table.Column<string>(nullable: true),
                    FIsKeyItem = table.Column<bool>(nullable: true),
                    FMaund = table.Column<int>(nullable: true),
                    FGrossWeight = table.Column<decimal>(nullable: true),
                    FNetWeight = table.Column<decimal>(nullable: true),
                    FCubicMeasure = table.Column<int>(nullable: true),
                    FLength = table.Column<decimal>(nullable: true),
                    FWidth = table.Column<decimal>(nullable: true),
                    FHeight = table.Column<decimal>(nullable: true),
                    FSize = table.Column<decimal>(nullable: true),
                    FVersion = table.Column<string>(nullable: true),
                    FStandardCost = table.Column<decimal>(nullable: true),
                    FStandardManHour = table.Column<decimal>(nullable: true),
                    FStdPayRate = table.Column<decimal>(nullable: true),
                    FChgFeeRate = table.Column<decimal>(nullable: true),
                    FStdFixFeeRate = table.Column<decimal>(nullable: true),
                    FOutMachFee = table.Column<decimal>(nullable: true),
                    FPieceRate = table.Column<decimal>(nullable: true),
                    FStdBatchQty = table.Column<decimal>(nullable: true),
                    FPOVAcctID = table.Column<int>(nullable: true),
                    FPIVAcctID = table.Column<int>(nullable: true),
                    FMCVAcctID = table.Column<int>(nullable: true),
                    FPCVAcctID = table.Column<int>(nullable: true),
                    FSLAcctID = table.Column<int>(nullable: true),
                    FCAVAcctID = table.Column<int>(nullable: true),
                    FCBAppendRate = table.Column<decimal>(nullable: true),
                    FCBAppendProject = table.Column<int>(nullable: true),
                    FCostBomID = table.Column<int>(nullable: true),
                    FCBRouting = table.Column<int>(nullable: true),
                    FOutMachFeeProject = table.Column<int>(nullable: true),
                    FInspectionLevel = table.Column<int>(nullable: true),
                    FInspectionProject = table.Column<int>(nullable: true),
                    FIsListControl = table.Column<int>(nullable: true),
                    FProChkMde = table.Column<int>(nullable: true),
                    FWWChkMde = table.Column<int>(nullable: true),
                    FSOChkMde = table.Column<int>(nullable: true),
                    FWthDrwChkMde = table.Column<int>(nullable: true),
                    FStkChkMde = table.Column<int>(nullable: true),
                    FOtherChkMde = table.Column<int>(nullable: true),
                    FStkChkPrd = table.Column<int>(nullable: true),
                    FStkChkAlrm = table.Column<int>(nullable: true),
                    FIdentifier = table.Column<int>(nullable: true),
                    FNameEn = table.Column<string>(nullable: true),
                    FModelEn = table.Column<string>(nullable: true),
                    FHSNumber = table.Column<int>(nullable: true),
                    FFirstUnit = table.Column<string>(nullable: true),
                    FSecondUnit = table.Column<string>(nullable: true),
                    FFirstUnitRate = table.Column<decimal>(nullable: true),
                    FSecondUnitRate = table.Column<decimal>(nullable: true),
                    FIsManage = table.Column<bool>(nullable: true),
                    FPackType = table.Column<int>(nullable: true),
                    FLenDecimal = table.Column<int>(nullable: true),
                    FCubageDecimal = table.Column<int>(nullable: true),
                    FWeightDecimal = table.Column<int>(nullable: true),
                    FImpostTaxRate = table.Column<decimal>(nullable: true),
                    FConsumeTaxRate = table.Column<decimal>(nullable: true),
                    FManageType = table.Column<int>(nullable: true),
                    FExportRate = table.Column<decimal>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_t_ICItem", x => x.FItemID);
                });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "t_ICItem");
        }
    }
}
