// <auto-generated />
using System;
using JIT.DIME2Barcode.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JIT.DIME2Barcode.Migrations
{
    [DbContext(typeof(ProductionPlanMySqlDbContext))]
    partial class ProductionPlanMySqlDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("JIT.DIME2Barcode.Entities.BillStatus", b =>
                {
                    b.Property<int>("FTranType")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FName");

                    b.Property<string>("FNote");

                    b.Property<int>("FStatus");

                    b.Property<string>("FTranName");

                    b.HasKey("FTranType");

                    b.ToTable("BillStatus");
                });

            modelBuilder.Entity("JIT.DIME2Barcode.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("FDepartment");

                    b.Property<int?>("FERPOfficeClerk");

                    b.Property<int?>("FERPUser");

                    b.Property<string>("FEmailAddress");

                    b.Property<DateTime?>("FHiredate");

                    b.Property<string>("FMpno")
                        .HasMaxLength(100);

                    b.Property<string>("FName")
                        .HasMaxLength(10);

                    b.Property<int>("FOrganizationUnitId");

                    b.Property<int?>("FParentId");

                    b.Property<string>("FPhone");

                    b.Property<int?>("FSex");

                    b.Property<int?>("FSystemUser");

                    b.Property<int>("FTenantId");

                    b.Property<long>("FUserId");

                    b.Property<int?>("FWorkingState");

                    b.Property<bool>("IsDeleted");

                    b.HasKey("Id");

                    b.HasIndex("FDepartment");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("JIT.DIME2Barcode.Entities.EqiupmentShift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("FEmployeeID");

                    b.Property<int>("FEqiupmentID");

                    b.Property<string>("FShift");

                    b.HasKey("Id");

                    b.HasIndex("FEmployeeID");

                    b.HasIndex("FEqiupmentID");

                    b.ToTable("T_EquimentShift");
                });

            modelBuilder.Entity("JIT.DIME2Barcode.Entities.Equipment", b =>
                {
                    b.Property<int>("FInterID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationTime");

                    b.Property<long?>("CreatorUserId");

                    b.Property<long?>("DeleterUserId");

                    b.Property<DateTime?>("DeletionTime");

                    b.Property<int>("FDayWorkHours");

                    b.Property<int>("FLift");

                    b.Property<int>("FMaxWorkHours");

                    b.Property<string>("FName");

                    b.Property<string>("FNumber");

                    b.Property<int>("FResidualLife");

                    b.Property<decimal>("FRunsRate");

                    b.Property<int>("FStatus");

                    b.Property<int>("FSwichTime");

                    b.Property<int>("FTimeUnit");

                    b.Property<int>("FType");

                    b.Property<int?>("FWorkCenterID");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Note");

                    b.HasKey("FInterID");

                    b.HasIndex("FNumber")
                        .IsUnique();

                    b.HasIndex("FWorkCenterID");

                    b.ToTable("t_equipment");
                });

            modelBuilder.Entity("JIT.DIME2Barcode.Entities.ICBOM", b =>
                {
                    b.Property<int>("FInterID")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("FAUXQTY");

                    b.Property<int>("FAccessories");

                    b.Property<DateTime?>("FAudDate");

                    b.Property<int>("FAuxPropID");

                    b.Property<string>("FBOMNumber");

                    b.Property<short>("FBOMSkip");

                    b.Property<bool?>("FBeenChecked");

                    b.Property<int>("FBomType");

                    b.Property<string>("FBrNo");

                    b.Property<bool?>("FCancellation");

                    b.Property<DateTime?>("FCheckDate");

                    b.Property<int?>("FCheckID");

                    b.Property<int?>("FCheckerID");

                    b.Property<int?>("FClassTypeID");

                    b.Property<int>("FCustID");

                    b.Property<int>("FCustItemID");

                    b.Property<int>("FEcnInterID");

                    b.Property<DateTime?>("FEnterTime");

                    b.Property<short>("FForbid");

                    b.Property<short>("FImpMode");

                    b.Property<int>("FItemID");

                    b.Property<string>("FNote");

                    b.Property<int?>("FOperatorID");

                    b.Property<DateTime?>("FPDMImportDate");

                    b.Property<int?>("FParentID");

                    b.Property<decimal>("FQty");

                    b.Property<int>("FRoutingID");

                    b.Property<short>("FStatus");

                    b.Property<int>("FTranType");

                    b.Property<int>("FUnitID");

                    b.Property<DateTime?>("FUseDate");

                    b.Property<int?>("FUseStatus");

                    b.Property<int?>("FUserID");

                    b.Property<string>("FVersion");

                    b.Property<decimal?>("FYield");

                    b.HasKey("FInterID");

                    b.ToTable("ICBOM");
                });

            modelBuilder.Entity("JIT.DIME2Barcode.Entities.ICException", b =>
                {
                    b.Property<string>("FID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FBiller");

                    b.Property<string>("FNote");

                    b.Property<DateTime?>("FRecoverTime");

                    b.Property<string>("FRemark");

                    b.Property<string>("FSrcID");

                    b.Property<DateTime?>("FTime");

                    b.HasKey("FID");

                    b.ToTable("ICException");
                });

            modelBuilder.Entity("JIT.DIME2Barcode.Entities.ICItem_Sync", b =>
                {
                    b.Property<int>("FItemID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FABCCls");

                    b.Property<int?>("FAPAcctID");

                    b.Property<int?>("FARAcctID");

                    b.Property<int?>("FAcctID");

                    b.Property<int?>("FAdminAcctID");

                    b.Property<string>("FAlias");

                    b.Property<string>("FApproveNo");

                    b.Property<int?>("FAuxClassID");

                    b.Property<int?>("FBackFlushSPID");

                    b.Property<int?>("FBackFlushStockID");

                    b.Property<decimal?>("FBatChangeEconomy");

                    b.Property<decimal?>("FBatFixEconomy");

                    b.Property<decimal?>("FBatchAppendQty");

                    b.Property<bool?>("FBatchManager");

                    b.Property<double?>("FBatchQty");

                    b.Property<int?>("FBeforeExpire");

                    b.Property<bool?>("FBookPlan");

                    b.Property<string>("FBrNo");

                    b.Property<int?>("FCAVAcctID");

                    b.Property<int?>("FCBAppendProject");

                    b.Property<decimal?>("FCBAppendRate");

                    b.Property<int?>("FCBBmStandardID");

                    b.Property<int?>("FCBRestore");

                    b.Property<int?>("FCBRouting");

                    b.Property<int?>("FCUUnitID");

                    b.Property<int?>("FCharSourceItemID");

                    b.Property<string>("FChartNumber");

                    b.Property<int?>("FCheckCycUnit");

                    b.Property<int?>("FCheckCycle");

                    b.Property<decimal?>("FChgFeeRate");

                    b.Property<bool?>("FClass");

                    b.Property<decimal?>("FConsumeTaxRate");

                    b.Property<string>("FContainerName");

                    b.Property<int?>("FCostAcctID");

                    b.Property<int?>("FCostBomID");

                    b.Property<double?>("FCostDiffRate");

                    b.Property<int?>("FCostProject");

                    b.Property<int?>("FCtrlStraregy");

                    b.Property<int?>("FCtrlType");

                    b.Property<int?>("FCubageDecimal");

                    b.Property<int?>("FCubicMeasure");

                    b.Property<decimal?>("FDailyConsume");

                    b.Property<int?>("FDaysPer");

                    b.Property<int?>("FDefaultLoc");

                    b.Property<int?>("FDefaultRoutingID");

                    b.Property<int?>("FDefaultWorkTypeID");

                    b.Property<short?>("FDeleted");

                    b.Property<int?>("FDepartment");

                    b.Property<string>("FEquipmentNum");

                    b.Property<int?>("FErpClsID");

                    b.Property<decimal?>("FExportRate");

                    b.Property<string>("FFirstUnit");

                    b.Property<decimal?>("FFirstUnitRate");

                    b.Property<float?>("FFixLeadTime");

                    b.Property<bool?>("FForSale");

                    b.Property<string>("FFullName");

                    b.Property<int?>("FGoodSpec");

                    b.Property<decimal?>("FGrossWeight");

                    b.Property<int?>("FHSNumber");

                    b.Property<decimal?>("FHeight");

                    b.Property<string>("FHelpCode");

                    b.Property<decimal?>("FHighLimit");

                    b.Property<bool?>("FISKFPeriod");

                    b.Property<int?>("FIdentifier");

                    b.Property<decimal?>("FImpostTaxRate");

                    b.Property<decimal?>("FInHighLimit");

                    b.Property<decimal?>("FInLowLimit");

                    b.Property<int?>("FInspectionLevel");

                    b.Property<int?>("FInspectionProject");

                    b.Property<int?>("FIsBackFlush");

                    b.Property<int?>("FIsCharSourceItem");

                    b.Property<bool?>("FIsEquipment");

                    b.Property<bool?>("FIsKeyItem");

                    b.Property<int?>("FIsListControl");

                    b.Property<bool?>("FIsManage");

                    b.Property<bool?>("FIsSale");

                    b.Property<bool?>("FIsSnManage");

                    b.Property<bool?>("FIsSparePart");

                    b.Property<bool?>("FIsSpecialTax");

                    b.Property<decimal?>("FKFPeriod");

                    b.Property<int?>("FKanBanCapability");

                    b.Property<DateTime?>("FLastCheckDate");

                    b.Property<float?>("FLeadTime");

                    b.Property<int?>("FLenDecimal");

                    b.Property<decimal?>("FLength");

                    b.Property<decimal?>("FLowLimit");

                    b.Property<int?>("FLowestBomCode");

                    b.Property<int?>("FMCVAcctID");

                    b.Property<bool?>("FMRPCon");

                    b.Property<bool?>("FMRPOrder");

                    b.Property<int?>("FManageType");

                    b.Property<int?>("FMaund");

                    b.Property<string>("FModel");

                    b.Property<string>("FModelEn");

                    b.Property<byte[]>("FModifyTime");

                    b.Property<string>("FName");

                    b.Property<string>("FNameEn");

                    b.Property<decimal?>("FNetWeight");

                    b.Property<string>("FNote");

                    b.Property<string>("FNumber");

                    b.Property<decimal?>("FOIHighLimit");

                    b.Property<decimal?>("FOILowLimit");

                    b.Property<short?>("FOmortize");

                    b.Property<short?>("FOmortizeScale");

                    b.Property<int?>("FOrderInterVal");

                    b.Property<int?>("FOrderMethod");

                    b.Property<decimal?>("FOrderPoint");

                    b.Property<double?>("FOrderPrice");

                    b.Property<int?>("FOrderRector");

                    b.Property<int?>("FOrderTrategy");

                    b.Property<int?>("FOrderUnitID");

                    b.Property<int?>("FOtherChkMde");

                    b.Property<decimal?>("FOutMachFee");

                    b.Property<int?>("FOutMachFeeProject");

                    b.Property<int?>("FPCVAcctID");

                    b.Property<int?>("FPIVAcctID");

                    b.Property<int?>("FPOHghPrcMnyType");

                    b.Property<decimal?>("FPOHighPrice");

                    b.Property<int?>("FPOVAcctID");

                    b.Property<int?>("FPackType");

                    b.Property<int?>("FParentID");

                    b.Property<double?>("FPerWastage");

                    b.Property<decimal?>("FPickHighLimit");

                    b.Property<decimal?>("FPickLowLimit");

                    b.Property<decimal?>("FPieceRate");

                    b.Property<short?>("FPlanClass");

                    b.Property<int?>("FPlanMode");

                    b.Property<int?>("FPlanPoint");

                    b.Property<decimal?>("FPlanPrice");

                    b.Property<short?>("FPlanPriceMethod");

                    b.Property<int?>("FPlanTrategy");

                    b.Property<int?>("FPlanner");

                    b.Property<int?>("FPreDeadLine");

                    b.Property<short?>("FPriceDecimal");

                    b.Property<int?>("FPriceFixingType");

                    b.Property<int?>("FProChkMde");

                    b.Property<int?>("FProductPrincipal");

                    b.Property<int?>("FProductUnitID");

                    b.Property<decimal?>("FProfitRate");

                    b.Property<bool?>("FPutInteger");

                    b.Property<short?>("FQtyDecimal");

                    b.Property<decimal?>("FQtyMax");

                    b.Property<decimal?>("FQtyMin");

                    b.Property<short?>("FRP");

                    b.Property<int?>("FRequirePoint");

                    b.Property<int?>("FSLAcctID");

                    b.Property<int?>("FSOChkMde");

                    b.Property<decimal?>("FSOHighLimit");

                    b.Property<decimal?>("FSOLowLimit");

                    b.Property<decimal?>("FSOLowPrc");

                    b.Property<int?>("FSOLowPrcMnyType");

                    b.Property<int?>("FSPID");

                    b.Property<int?>("FSaleAcctID");

                    b.Property<decimal?>("FSalePrice");

                    b.Property<int?>("FSalePriceFixingType");

                    b.Property<int?>("FSaleTaxAcctID");

                    b.Property<int?>("FSaleUnitID");

                    b.Property<decimal?>("FSecCoefficient");

                    b.Property<decimal?>("FSecInv");

                    b.Property<int?>("FSecUnitDecimal");

                    b.Property<int?>("FSecUnitID");

                    b.Property<string>("FSecondUnit");

                    b.Property<decimal?>("FSecondUnitRate");

                    b.Property<int?>("FSerialClassID");

                    b.Property<string>("FShortNumber");

                    b.Property<decimal?>("FSize");

                    b.Property<int?>("FSource");

                    b.Property<double?>("FStaCost");

                    b.Property<decimal?>("FStandardCost");

                    b.Property<decimal?>("FStandardManHour");

                    b.Property<decimal?>("FStdBatchQty");

                    b.Property<decimal?>("FStdFixFeeRate");

                    b.Property<decimal?>("FStdPayRate");

                    b.Property<int?>("FStkChkAlrm");

                    b.Property<int?>("FStkChkMde");

                    b.Property<int?>("FStkChkPrd");

                    b.Property<decimal?>("FStockPrice");

                    b.Property<bool?>("FStockTime");

                    b.Property<int?>("FStoreUnitID");

                    b.Property<int?>("FTaxRate");

                    b.Property<int?>("FTopID");

                    b.Property<int?>("FTotalTQQ");

                    b.Property<int?>("FTrack");

                    b.Property<int?>("FTypeID");

                    b.Property<int?>("FUnitGroupID");

                    b.Property<int?>("FUnitID");

                    b.Property<int?>("FUseState");

                    b.Property<string>("FVersion");

                    b.Property<int?>("FWWChkMde");

                    b.Property<decimal?>("FWWHghPrc");

                    b.Property<int?>("FWWHghPrcMnyType");

                    b.Property<int?>("FWeightDecimal");

                    b.Property<decimal?>("FWidth");

                    b.Property<int?>("FWthDrwChkMde");

                    b.Property<double?>("F_102");

                    b.Property<double?>("F_103");

                    b.Property<string>("F_104");

                    b.Property<int?>("F_105");

                    b.Property<int?>("F_106");

                    b.Property<string>("F_107");

                    b.Property<int?>("F_108");

                    b.HasKey("FItemID");

                    b.ToTable("t_ICItem");
                });

            modelBuilder.Entity("JIT.DIME2Barcode.Entities.ICMO", b =>
                {
                    b.Property<int>("FInterID")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("FAuxCheckCommitQty");

                    b.Property<decimal>("FAuxCommitQty");

                    b.Property<decimal>("FAuxInHighLimitQty");

                    b.Property<decimal>("FAuxInLowLimitQty");

                    b.Property<decimal>("FAuxQty");

                    b.Property<decimal>("FAuxQtyBack");

                    b.Property<decimal>("FAuxQtyFinish");

                    b.Property<decimal?>("FAuxQtyForItem");

                    b.Property<decimal>("FAuxQtyLost");

                    b.Property<decimal>("FAuxQtyPass");

                    b.Property<decimal>("FAuxQtyScrap");

                    b.Property<decimal>("FAuxStockQty");

                    b.Property<string>("FBillNo");

                    b.Property<int?>("FBillerID");

                    b.Property<int>("FBomInterID");

                    b.Property<string>("FBrNo");

                    b.Property<bool?>("FCancellation");

                    b.Property<int>("FCardClosed");

                    b.Property<int>("FChangeTimes");

                    b.Property<decimal>("FCheckCommitQty");

                    b.Property<DateTime?>("FCheckDate");

                    b.Property<int?>("FCheckerID");

                    b.Property<DateTime?>("FCloseDate");

                    b.Property<short>("FClosed");

                    b.Property<DateTime?>("FCommitDate");

                    b.Property<decimal>("FCommitQty");

                    b.Property<DateTime?>("FConfirmDate");

                    b.Property<int?>("FConfirmerID");

                    b.Property<int?>("FConveyerID");

                    b.Property<int>("FCostObjID");

                    b.Property<int?>("FCurCheckLevel");

                    b.Property<int>("FCustID");

                    b.Property<int>("FFinClosed");

                    b.Property<DateTime?>("FFinClosedate");

                    b.Property<int?>("FFinCloseer");

                    b.Property<DateTime?>("FFinishDate");

                    b.Property<decimal>("FFinishTime");

                    b.Property<decimal>("FFixTime");

                    b.Property<string>("FGMPBatchNo");

                    b.Property<decimal>("FGMPBulkQty");

                    b.Property<decimal>("FGMPCollectRate");

                    b.Property<decimal>("FGMPItemBalance");

                    b.Property<decimal>("FHRReadyTime");

                    b.Property<int>("FHandworkClose");

                    b.Property<decimal>("FInHighLimit");

                    b.Property<decimal>("FInHighLimitQty");

                    b.Property<decimal>("FInLowLimit");

                    b.Property<decimal>("FInLowLimitQty");

                    b.Property<int>("FItemID");

                    b.Property<short>("FMRP");

                    b.Property<int>("FMRPLockFlag");

                    b.Property<string>("FMTONo");

                    b.Property<int>("FMrpClosed");

                    b.Property<DateTime?>("FMultiCheckDate1");

                    b.Property<DateTime?>("FMultiCheckDate2");

                    b.Property<DateTime?>("FMultiCheckDate3");

                    b.Property<DateTime?>("FMultiCheckDate4");

                    b.Property<DateTime?>("FMultiCheckDate5");

                    b.Property<DateTime?>("FMultiCheckDate6");

                    b.Property<int?>("FMultiCheckLevel1");

                    b.Property<int?>("FMultiCheckLevel2");

                    b.Property<int?>("FMultiCheckLevel3");

                    b.Property<int?>("FMultiCheckLevel4");

                    b.Property<int?>("FMultiCheckLevel5");

                    b.Property<int?>("FMultiCheckLevel6");

                    b.Property<string>("FNote");

                    b.Property<int?>("FOrderInterID");

                    b.Property<int?>("FPPOrderInterID");

                    b.Property<int?>("FParentInterID");

                    b.Property<DateTime?>("FPlanCommitDate");

                    b.Property<int>("FPlanConfirmed");

                    b.Property<DateTime?>("FPlanFinishDate");

                    b.Property<DateTime?>("FPlanIssueDate");

                    b.Property<int>("FPlanMode");

                    b.Property<int>("FPlanOrderInterID");

                    b.Property<decimal>("FPowerCutTime");

                    b.Property<int>("FPrintCount");

                    b.Property<decimal>("FProcessFee");

                    b.Property<decimal>("FProcessPrice");

                    b.Property<int?>("FProductionLineID");

                    b.Property<int?>("FProjectNO");

                    b.Property<decimal>("FQty");

                    b.Property<decimal>("FQtyBack");

                    b.Property<decimal>("FQtyFinish");

                    b.Property<decimal?>("FQtyForItem");

                    b.Property<decimal>("FQtyLost");

                    b.Property<decimal>("FQtyPass");

                    b.Property<decimal>("FQtyScrap");

                    b.Property<decimal>("FReadyTIme");

                    b.Property<decimal>("FReleasedAuxQty");

                    b.Property<decimal>("FReleasedQty");

                    b.Property<int?>("FRequesterID");

                    b.Property<int?>("FRoutingID");

                    b.Property<int>("FScheduleID");

                    b.Property<short>("FSourceEntryID");

                    b.Property<DateTime?>("FStartDate");

                    b.Property<int>("FStartFlag");

                    b.Property<short>("FStatus");

                    b.Property<int>("FStockFlag");

                    b.Property<decimal>("FStockQty");

                    b.Property<int>("FSubEntryID");

                    b.Property<int?>("FSupplyID");

                    b.Property<bool?>("FSuspend");

                    b.Property<int>("FTaskID");

                    b.Property<short>("FTranType");

                    b.Property<short?>("FType");

                    b.Property<decimal>("FUnScheduledAuxQty");

                    b.Property<decimal>("FUnScheduledQty");

                    b.Property<int>("FUnitID");

                    b.Property<string>("FVchBillNo");

                    b.Property<int>("FVchInterID");

                    b.Property<decimal>("FWaitItemTime");

                    b.Property<decimal>("FWaitToolTime");

                    b.Property<int?>("FWorkShop");

                    b.Property<int>("FWorkTypeID");

                    b.HasKey("FInterID");

                    b.ToTable("ICMO");
                });

            modelBuilder.Entity("JIT.DIME2Barcode.Entities.ICMODaily", b =>
                {
                    b.Property<string>("FID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FBillNo");

                    b.Property<DateTime?>("FBillTime")
                        .HasColumnType("datetime");

                    b.Property<string>("FBiller");

                    b.Property<DateTime?>("FCheckTime")
                        .HasColumnType("datetime");

                    b.Property<string>("FChecker");

                    b.Property<DateTime?>("FCloseTime")
                        .HasColumnType("datetime");

                    b.Property<bool?>("FClosed");

                    b.Property<string>("FCloser");

                    b.Property<decimal?>("FCommitAuxQty");

                    b.Property<DateTime>("FDate")
                        .HasColumnType("datetime");

                    b.Property<int>("FEntryID");

                    b.Property<decimal?>("FFailAuxQty");

                    b.Property<decimal?>("FFinishAuxQty");

                    b.Property<string>("FMOBillNo");

                    b.Property<int?>("FMOInterID");

                    b.Property<int?>("FMachineID");

                    b.Property<string>("FNote");

                    b.Property<int?>("FOperID");

                    b.Property<string>("FOperNote");

                    b.Property<decimal?>("FPassAuxQty");

                    b.Property<decimal?>("FPlanAuxQty");

                    b.Property<int?>("FShift");

                    b.Property<string>("FSrcID");

                    b.Property<int>("FStatus");

                    b.Property<int?>("FTranType");

                    b.Property<int?>("FWorkCenterID");

                    b.Property<string>("FWorkCenterName");

                    b.Property<int?>("FWorker");

                    b.HasKey("FID");

                    b.HasIndex("FSrcID");

                    b.ToTable("ICMODaily");
                });

            modelBuilder.Entity("JIT.DIME2Barcode.Entities.ICMODispBill", b =>
                {
                    b.Property<string>("FID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FBillNo");

                    b.Property<DateTime?>("FBillTime");

                    b.Property<string>("FBiller");

                    b.Property<DateTime?>("FCheckTime");

                    b.Property<string>("FChecker");

                    b.Property<DateTime?>("FCloseTime");

                    b.Property<bool?>("FClosed");

                    b.Property<string>("FCloser");

                    b.Property<decimal?>("FCommitAuxQty");

                    b.Property<DateTime?>("FDate");

                    b.Property<decimal?>("FFInspectAuxQty");

                    b.Property<decimal?>("FFailAuxQty");

                    b.Property<decimal?>("FFinishAuxQty");

                    b.Property<string>("FMOBillNo");

                    b.Property<int?>("FMOInterID");

                    b.Property<int?>("FMachineID");

                    b.Property<string>("FNote");

                    b.Property<int?>("FOperID");

                    b.Property<decimal?>("FPassAuxQty");

                    b.Property<decimal?>("FPlanAuxQty");

                    b.Property<int>("FPrintCount");

                    b.Property<int?>("FShift");

                    b.Property<string>("FSrcID");

                    b.Property<int>("FStatus");

                    b.Property<int>("FTranType");

                    b.Property<int?>("FWorkCenterID");

                    b.Property<int>("FWorker");

                    b.HasKey("FID");

                    b.ToTable("ICMODispBill");
                });

            modelBuilder.Entity("JIT.DIME2Barcode.Entities.ICMOInspectBill", b =>
                {
                    b.Property<string>("FID")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal?>("FAuxQty");

                    b.Property<string>("FBillNo");

                    b.Property<DateTime?>("FBillTime");

                    b.Property<string>("FBiller");

                    b.Property<decimal?>("FCheckAuxQty");

                    b.Property<DateTime?>("FCheckTime");

                    b.Property<string>("FChecker");

                    b.Property<decimal?>("FFailAuxQty");

                    b.Property<decimal?>("FFailAuxQtyM");

                    b.Property<decimal?>("FFailAuxQtyP");

                    b.Property<DateTime?>("FInspectTime");

                    b.Property<string>("FInspector");

                    b.Property<int?>("FMOInterID");

                    b.Property<int?>("FMachineID");

                    b.Property<string>("FNote");

                    b.Property<int?>("FOperID");

                    b.Property<decimal?>("FPassAuxQty");

                    b.Property<decimal?>("FPassAuxQtyM");

                    b.Property<decimal?>("FPassAuxQtyP");

                    b.Property<int>("FStatus");

                    b.Property<int>("FTranType");

                    b.Property<int?>("FWorkcenterID");

                    b.Property<string>("FWorker");

                    b.HasKey("FID");

                    b.ToTable("ICMOInspectBill");
                });

            modelBuilder.Entity("JIT.DIME2Barcode.Entities.ICMOSchedule", b =>
                {
                    b.Property<string>("FID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FBillNo");

                    b.Property<DateTime?>("FBillTime");

                    b.Property<string>("FBiller");

                    b.Property<bool?>("FCancellation");

                    b.Property<DateTime?>("FCheckTime");

                    b.Property<string>("FChecker");

                    b.Property<DateTime?>("FCloseTime");

                    b.Property<bool?>("FClosed");

                    b.Property<string>("FCloser");

                    b.Property<decimal?>("FFailAuxQty");

                    b.Property<decimal?>("FFinishAuxQty");

                    b.Property<DateTime?>("FFinishDate");

                    b.Property<int>("FItemID");

                    b.Property<string>("FItemModel");

                    b.Property<string>("FItemName");

                    b.Property<string>("FItemNumber");

                    b.Property<string>("FMOBillNo");

                    b.Property<int>("FMOInterID");

                    b.Property<string>("FNote");

                    b.Property<decimal?>("FPassAuxQty");

                    b.Property<decimal?>("FPlanAuxQty");

                    b.Property<DateTime?>("FPlanBeginDate");

                    b.Property<DateTime?>("FPlanFinishDate");

                    b.Property<decimal?>("FSrcAuxQty");

                    b.Property<int>("FStatus");

                    b.Property<int>("FTranType");

                    b.HasKey("FID");

                    b.ToTable("ICMOSchedule");
                });

            modelBuilder.Entity("JIT.DIME2Barcode.Entities.ICMaterialPicking", b =>
                {
                    b.Property<string>("FID")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal?>("FAuxQty");

                    b.Property<string>("FBatchNo");

                    b.Property<string>("FBiller");

                    b.Property<DateTime?>("FDate");

                    b.Property<int>("FEntryID");

                    b.Property<int?>("FItemID");

                    b.Property<string>("FNote");

                    b.Property<string>("FSrcID");

                    b.Property<int?>("FUnitID");

                    b.HasKey("FID");

                    b.ToTable("ICMaterialPicking");
                });

            modelBuilder.Entity("JIT.DIME2Barcode.Entities.ICQualityRpt", b =>
                {
                    b.Property<string>("FID")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal?>("FAuxQty");

                    b.Property<int>("FItemID");

                    b.Property<string>("FNote");

                    b.Property<string>("FRemark");

                    b.Property<string>("ICMOInspectBillID");

                    b.HasKey("FID");

                    b.ToTable("ICMOQualityRpt");
                });

            modelBuilder.Entity("JIT.DIME2Barcode.Entities.OrganizationUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<DateTime?>("CreationTime");

                    b.Property<long?>("CreatorUserId");

                    b.Property<string>("DataBaseConnection");

                    b.Property<long?>("DeleterUserId");

                    b.Property<DateTime>("DeletionTime");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int?>("ERPOrganization");

                    b.Property<int?>("ERPOrganizationLeader");

                    b.Property<bool?>("IsDeleted");

                    b.Property<DateTime?>("LastModificationTime");

                    b.Property<int?>("LastModifierUserId");

                    b.Property<int?>("OrganizationType");

                    b.Property<int?>("ParentId");

                    b.Property<string>("Remark");

                    b.Property<int?>("TenantId");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("T_OrganizationUnit");
                });

            modelBuilder.Entity("JIT.DIME2Barcode.Entities.SEOrder", b =>
                {
                    b.Property<int>("FInterID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("FAreaPS");

                    b.Property<short>("FBClosed");

                    b.Property<string>("FBillNo");

                    b.Property<int?>("FBillerID");

                    b.Property<int?>("FBrID");

                    b.Property<string>("FBrNo");

                    b.Property<bool?>("FCancellation");

                    b.Property<string>("FCashDiscount");

                    b.Property<string>("FChangeCauses");

                    b.Property<DateTime?>("FChangeDate");

                    b.Property<int>("FChangeMark");

                    b.Property<int>("FChangeUser");

                    b.Property<DateTime?>("FCheckDate");

                    b.Property<int?>("FCheckerID");

                    b.Property<int>("FChildren");

                    b.Property<int>("FClassTypeID");

                    b.Property<short>("FClosed");

                    b.Property<string>("FConsignee");

                    b.Property<int?>("FCurCheckLevel");

                    b.Property<int?>("FCurrencyID");

                    b.Property<int?>("FCustID");

                    b.Property<DateTime?>("FDate");

                    b.Property<int?>("FDeptID");

                    b.Property<bool?>("FDiscountType");

                    b.Property<int>("FDrpRelateTranType");

                    b.Property<int?>("FEmpID");

                    b.Property<double?>("FExchangeRate");

                    b.Property<int>("FExchangeRateType");

                    b.Property<string>("FExplanation");

                    b.Property<string>("FFetchAdd");

                    b.Property<DateTime?>("FFetchDate");

                    b.Property<string>("FFetchStyle");

                    b.Property<int?>("FHeadSelfS0150");

                    b.Property<int?>("FHeadSelfS0151");

                    b.Property<DateTime?>("FHeadSelfS0153");

                    b.Property<int?>("FHeadSelfS0154");

                    b.Property<int>("FImport");

                    b.Property<short?>("FInvoiceClosed");

                    b.Property<int?>("FManageType");

                    b.Property<int?>("FMangerID");

                    b.Property<DateTime?>("FMultiCheckDate1");

                    b.Property<DateTime?>("FMultiCheckDate2");

                    b.Property<DateTime?>("FMultiCheckDate3");

                    b.Property<DateTime?>("FMultiCheckDate4");

                    b.Property<DateTime?>("FMultiCheckDate5");

                    b.Property<DateTime?>("FMultiCheckDate6");

                    b.Property<int?>("FMultiCheckLevel1");

                    b.Property<int?>("FMultiCheckLevel2");

                    b.Property<int?>("FMultiCheckLevel3");

                    b.Property<int?>("FMultiCheckLevel4");

                    b.Property<int?>("FMultiCheckLevel5");

                    b.Property<int?>("FMultiCheckLevel6");

                    b.Property<string>("FNote");

                    b.Property<byte[]>("FOperDate");

                    b.Property<int?>("FOrderAffirm");

                    b.Property<string>("FPOOrdBillNo");

                    b.Property<DateTime?>("FPayDate");

                    b.Property<string>("FPayStyle");

                    b.Property<short>("FPrintCount");

                    b.Property<int?>("FRelateBrID");

                    b.Property<int?>("FSaleStyle");

                    b.Property<int>("FSelTranType");

                    b.Property<DateTime?>("FSettleDate");

                    b.Property<int?>("FSettleID");

                    b.Property<short>("FStatus");

                    b.Property<short>("FSysStatus");

                    b.Property<int>("FSystemType");

                    b.Property<int?>("FTranStatus");

                    b.Property<int>("FTranType");

                    b.Property<float?>("FTransitAheadTime");

                    b.Property<Guid>("FUUID");

                    b.Property<string>("FValidaterName");

                    b.Property<string>("FVersionNo");

                    b.HasKey("FInterID");

                    b.ToTable("SEOrder");
                });

            modelBuilder.Entity("JIT.DIME2Barcode.Entities.SyncRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("LastSyncTime");

                    b.Property<int>("MaxRowVersion");

                    b.Property<string>("TableName");

                    b.HasKey("Id");

                    b.ToTable("t_SyncRecord");
                });

            modelBuilder.Entity("JIT.DIME2Barcode.Entities.TB_BadItemRelation", b =>
                {
                    b.Property<int>("FID")
                        .ValueGeneratedOnAdd();

                    b.Property<bool?>("FDeleted");

                    b.Property<int?>("FItemID");

                    b.Property<string>("FName");

                    b.Property<string>("FNumber");

                    b.Property<int>("FOperID");

                    b.Property<string>("FRemark");

                    b.HasKey("FID");

                    b.ToTable("TB_BadItemRelation");
                });

            modelBuilder.Entity("JIT.DIME2Barcode.Entities.T_PrintTemplate", b =>
                {
                    b.Property<string>("FInterID")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("FFile");

                    b.Property<string>("FFileDir");

                    b.Property<int>("FItemID");

                    b.Property<string>("FNote");

                    b.Property<int>("FTranType");

                    b.Property<string>("FType");

                    b.Property<int?>("FUserID");

                    b.HasKey("FInterID");

                    b.ToTable("T_PrintTemplate");
                });

            modelBuilder.Entity("JIT.DIME2Barcode.Entities.VW_Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("FDepartment");

                    b.Property<int>("FERPOfficeClerk");

                    b.Property<int>("FERPUser");

                    b.Property<string>("FEmailAddress");

                    b.Property<DateTime>("FHiredate");

                    b.Property<string>("FMpno");

                    b.Property<string>("FName");

                    b.Property<int>("FOrganizationUnitId");

                    b.Property<int>("FParentId");

                    b.Property<string>("FPhone");

                    b.Property<int>("FSex");

                    b.Property<int>("FSystemUser");

                    b.Property<int>("FTenantId");

                    b.Property<long>("FUserId");

                    b.Property<int>("FWorkingState");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("fatherName");

                    b.Property<string>("remark");

                    b.Property<string>("rolename");

                    b.Property<string>("zsonName");

                    b.HasKey("Id");

                    b.ToTable("VW_Employee");
                });

            modelBuilder.Entity("JIT.DIME2Barcode.Entities.VW_Group_ICMODaily", b =>
                {
                    b.Property<string>("FID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FMOBillNo");

                    b.Property<int?>("FMOInterID");

                    b.Property<decimal?>("合格数量");

                    b.Property<decimal?>("完成数量");

                    b.Property<string>("操作员");

                    b.Property<DateTime?>("日期");

                    b.Property<string>("机台");

                    b.Property<decimal?>("派工数量");

                    b.Property<string>("班次");

                    b.Property<decimal>("计划数量");

                    b.HasKey("FID");

                    b.ToTable("VW_Group_ICMODaily");
                });

            modelBuilder.Entity("JIT.DIME2Barcode.Entities.VW_ICMODaily", b =>
                {
                    b.Property<string>("计划单号")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FID");

                    b.Property<string>("产品名称");

                    b.Property<string>("产品编码");

                    b.Property<string>("任务单号");

                    b.Property<decimal?>("完成数量");

                    b.Property<DateTime?>("日期");

                    b.Property<string>("规格型号");

                    b.Property<DateTime?>("计划完工日期");

                    b.Property<DateTime?>("计划开工日期");

                    b.Property<decimal?>("计划数量");

                    b.Property<int>("车间");

                    b.HasKey("计划单号");

                    b.ToTable("VW_ICMODaily");
                });

            modelBuilder.Entity("JIT.DIME2Barcode.Entities.VW_MODispBillList", b =>
                {
                    b.Property<string>("FID")
                        .ValueGeneratedOnAdd();

                    b.Property<bool?>("FClosed");

                    b.Property<int>("FItemID");

                    b.Property<int>("FOperID");

                    b.Property<int>("FStatus");

                    b.Property<int?>("FWorkcenterID");

                    b.Property<string>("FsrcID");

                    b.Property<decimal?>("不合格数量");

                    b.Property<string>("产品代码");

                    b.Property<string>("产品名称");

                    b.Property<decimal?>("合格数量");

                    b.Property<string>("工作中心");

                    b.Property<string>("工序");

                    b.Property<int>("打印次数");

                    b.Property<long>("操作者");

                    b.Property<decimal?>("汇报数量");

                    b.Property<string>("派工单号");

                    b.Property<decimal?>("派工数量");

                    b.Property<int?>("班次");

                    b.Property<string>("生产任务");

                    b.Property<DateTime>("生产日期");

                    b.Property<string>("规格型号");

                    b.Property<DateTime>("计划完工日期");

                    b.Property<DateTime>("计划开工日期");

                    b.Property<decimal?>("计划数量");

                    b.Property<string>("设备");

                    b.HasKey("FID");

                    b.ToTable("VW_MODispBillList");
                });

            modelBuilder.Entity("JIT.DIME2Barcode.Entities.t_Department", b =>
                {
                    b.Property<int>("FItemID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("FAcctID");

                    b.Property<string>("FBrNO");

                    b.Property<int>("FCalID");

                    b.Property<int>("FCostAccountType");

                    b.Property<int>("FDProperty");

                    b.Property<int?>("FDStock");

                    b.Property<short>("FDeleted");

                    b.Property<string>("FFax");

                    b.Property<bool?>("FIsCreditMgr");

                    b.Property<int?>("FManager");

                    b.Property<byte[]>("FModifyTime");

                    b.Property<string>("FName");

                    b.Property<string>("FNote");

                    b.Property<string>("FNumber");

                    b.Property<int>("FOtherAPAcctID");

                    b.Property<int>("FOtherARAcctID");

                    b.Property<int?>("FParentID");

                    b.Property<string>("FPhone");

                    b.Property<int?>("FPlanArea");

                    b.Property<int>("FPreAPAcctID");

                    b.Property<int>("FPreARAcctID");

                    b.Property<string>("FShortNumber");

                    b.HasKey("FItemID");

                    b.ToTable("t_Department");
                });

            modelBuilder.Entity("JIT.DIME2Barcode.Entities.t_MeasureUnit", b =>
                {
                    b.Property<int>("FMeasureUnitID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FAuxClass");

                    b.Property<string>("FBrNo");

                    b.Property<decimal>("FCoefficient");

                    b.Property<short>("FControl");

                    b.Property<int?>("FConversation");

                    b.Property<short>("FDeleted");

                    b.Property<int>("FItemID");

                    b.Property<byte[]>("FModifyTime");

                    b.Property<string>("FName");

                    b.Property<string>("FNameEN");

                    b.Property<string>("FNameEnPlu");

                    b.Property<string>("FNumber");

                    b.Property<string>("FOperDate");

                    b.Property<int?>("FParentID");

                    b.Property<int>("FPrecision");

                    b.Property<decimal>("FScale");

                    b.Property<string>("FShortNumber");

                    b.Property<short>("FStandard");

                    b.Property<int>("FSystemType");

                    b.Property<int>("FUnitGroupID");

                    b.Property<Guid>("UUID");

                    b.HasKey("FMeasureUnitID");

                    b.ToTable("t_MeasureUnit");
                });

            modelBuilder.Entity("JIT.DIME2Barcode.Entities.t_SubMessage", b =>
                {
                    b.Property<int>("FInterID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FBrNo");

                    b.Property<int>("FDeleted");

                    b.Property<int>("FDetail");

                    b.Property<string>("FID");

                    b.Property<byte[]>("FModifyTime");

                    b.Property<string>("FName");

                    b.Property<int>("FParentID");

                    b.Property<string>("FSpec");

                    b.Property<int>("FSystemType");

                    b.Property<int>("FTypeID");

                    b.Property<string>("UUID");

                    b.HasKey("FInterID");

                    b.ToTable("t_SubMessage");
                });

            modelBuilder.Entity("JIT.DIME2Barcode.TaskAssignment.ICMODaily.Dtos.VW_ICMODaily_Group_By_Day", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DisplayName");

                    b.Property<DateTime>("FDate");

                    b.Property<int>("FItemID");

                    b.Property<string>("FItemModel");

                    b.Property<string>("FItemName");

                    b.Property<string>("FItemNumber");

                    b.Property<string>("FMOBillNo");

                    b.Property<decimal>("TotalPlanAuxQty");

                    b.HasKey("Id");

                    b.ToTable("VW_ICMODaily_Group_By_Day");
                });

            modelBuilder.Entity("JIT.DIME2Barcode.TaskAssignment.ICMODispBill.Dtos.VW_DispatchBill_List", b =>
                {
                    b.Property<string>("FID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FBillNo");

                    b.Property<DateTime?>("FBillTime");

                    b.Property<string>("FBiller");

                    b.Property<decimal?>("FCommitAuxQty");

                    b.Property<DateTime>("FDate");

                    b.Property<string>("FMOBillNo");

                    b.Property<int>("FMOInterID");

                    b.Property<int>("FMachineID");

                    b.Property<string>("FShift");

                    b.Property<int>("FShiftID");

                    b.Property<int>("FWorkerID");

                    b.Property<string>("Machine");

                    b.Property<string>("Worker");

                    b.HasKey("FID");

                    b.ToTable("VW_DispatchBill_List");
                });

            modelBuilder.Entity("JIT.DIME2Barcode.Entities.Employee", b =>
                {
                    b.HasOne("JIT.DIME2Barcode.Entities.OrganizationUnit", "Department")
                        .WithMany()
                        .HasForeignKey("FDepartment");
                });

            modelBuilder.Entity("JIT.DIME2Barcode.Entities.EqiupmentShift", b =>
                {
                    b.HasOne("JIT.DIME2Barcode.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("FEmployeeID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("JIT.DIME2Barcode.Entities.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("FEqiupmentID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JIT.DIME2Barcode.Entities.Equipment", b =>
                {
                    b.HasOne("JIT.DIME2Barcode.Entities.OrganizationUnit", "WorkCenter")
                        .WithMany()
                        .HasForeignKey("FWorkCenterID");
                });

            modelBuilder.Entity("JIT.DIME2Barcode.Entities.ICMODaily", b =>
                {
                    b.HasOne("JIT.DIME2Barcode.Entities.ICMOSchedule", "Schedule")
                        .WithMany("Dailies")
                        .HasForeignKey("FSrcID");
                });

            modelBuilder.Entity("JIT.DIME2Barcode.Entities.OrganizationUnit", b =>
                {
                    b.HasOne("JIT.DIME2Barcode.Entities.OrganizationUnit", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");
                });
#pragma warning restore 612, 618
        }
    }
}
