//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityGerneraLib
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DIME2BarcodeContainer : DbContext
    {
        public DIME2BarcodeContainer()
            : base("name=DIME2BarcodeContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<t_ICItem> t_ICItem { get; set; }
        public virtual DbSet<VW_MOBillList> VW_MOBillList { get; set; }
        public virtual DbSet<VW_ICMODaily> VW_ICMODaily { get; set; }
        public virtual DbSet<VW_ICMODispBill_By_Date> VW_ICMODispBill_By_Date { get; set; }
        public virtual DbSet<VW_ICMOInspectBillList> VW_ICMOInspectBillList { get; set; }
        public virtual DbSet<VW_Group_ICMODaily> VW_Group_ICMODaily { get; set; }
    }
}
