//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityGerneraLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Resource
    {
        public int FInterID { get; set; }
        public string FNumber { get; set; }
        public string FName { get; set; }
        public int FType { get; set; }
        public Nullable<int> FWorkCenterID { get; set; }
        public Nullable<decimal> FUnitCost { get; set; }
        public Nullable<bool> FKey { get; set; }
        public int FRuns { get; set; }
        public decimal FHours { get; set; }
        public Nullable<decimal> FUseingRate { get; set; }
        public Nullable<decimal> FEfficiency { get; set; }
        public Nullable<int> FParentID { get; set; }
        public Nullable<bool> FDeleted { get; set; }
        public int FCalID { get; set; }
        public Nullable<int> FDeviceID { get; set; }
        public Nullable<decimal> FEIProductivity { get; set; }
    }
}
