//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityGerneraLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_ICMOInspectBillList
    {
        public string 派工单号 { get; set; }
        public string 产品名称 { get; set; }
        public Nullable<int> 工序 { get; set; }
        public Nullable<decimal> 汇报数 { get; set; }
        public Nullable<decimal> 合格数 { get; set; }
        public Nullable<decimal> 不合格数 { get; set; }
    }
}
